# Generated by Django 5.2.8 on 2025-12-06 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_boardgame_historicalboardgame_and_more'),
        ('lists', '0003_alter_customlist_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customlist',
            name='allow_recommendations',
            field=models.BooleanField(default=False, help_text='Allow anyone to recommend items to add to this list (only for public lists)'),
        ),
        migrations.AddField(
            model_name='customlist',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Allow anyone with the link to view this list (read-only)'),
        ),
        migrations.CreateModel(
            name='ListRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_name', models.CharField(blank=True, default='', help_text='Display name for anonymous recommenders', max_length=100)),
                ('date_recommended', models.DateTimeField(auto_now_add=True)),
                ('custom_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='lists.customlist')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('recommended_by', models.ForeignKey(blank=True, help_text='The user who recommended this item (null if anonymous)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_recommended'],
                'constraints': [models.UniqueConstraint(fields=('item', 'custom_list'), name='lists_listrecommendation_unique_item_list')],
            },
        ),
    ]
