# Generated by Django 5.2.8 on 2025-12-09 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0055_boardgame_historicalboardgame_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrobbleLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField(blank=True, null=True)),
                ('media_type', models.CharField(choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Board Game')], max_length=10)),
                ('title', models.CharField(max_length=500)),
                ('season', models.PositiveIntegerField(blank=True, null=True)),
                ('episode', models.PositiveIntegerField(blank=True, null=True)),
                ('action', models.CharField(max_length=20)),
                ('final_progress', models.FloatField()),
                ('was_scrobbled', models.BooleanField(default=False, help_text='Whether this resulted in marking the item as watched')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('player', models.CharField(blank=True, max_length=100)),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrobble_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ended_at'],
                'indexes': [models.Index(fields=['user', 'ended_at'], name='api_scrobbl_user_id_19e293_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScrobbleSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(blank=True, choices=[('tv', 'TV Show'), ('season', 'TV Season'), ('episode', 'Episode'), ('movie', 'Movie'), ('anime', 'Anime'), ('manga', 'Manga'), ('game', 'Game'), ('book', 'Book'), ('comic', 'Comic'), ('boardgame', 'Board Game')], max_length=10)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('season', models.PositiveIntegerField(blank=True, null=True)),
                ('episode', models.PositiveIntegerField(blank=True, null=True)),
                ('tmdb_id', models.CharField(blank=True, max_length=20)),
                ('imdb_id', models.CharField(blank=True, max_length=20)),
                ('tvdb_id', models.CharField(blank=True, max_length=20)),
                ('mal_id', models.CharField(blank=True, max_length=20)),
                ('progress', models.FloatField(default=0.0, help_text='Progress percentage (0-100)')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Total duration in seconds', null=True)),
                ('state', models.CharField(choices=[('watching', 'Watching'), ('paused', 'Paused'), ('stopped', 'Stopped')], default='watching', max_length=20)),
                ('player', models.CharField(blank=True, max_length=100)),
                ('player_version', models.CharField(blank=True, max_length=50)),
                ('client_id', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, help_text='Linked Yamtrack item (if found)', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrobble_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'state'], name='api_scrobbl_user_id_1e00b5_idx'), models.Index(fields=['updated_at'], name='api_scrobbl_updated_545067_idx')],
            },
        ),
    ]
