# Generated by Django 5.2.8 on 2025-12-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrobblesession',
            name='already_scrobbled',
            field=models.BooleanField(default=False, help_text='Whether this session has already been marked as watched'),
        ),
    ]
